### ISSUE TITLE
episode 4: GPU programming concepts

### ISSUE THREAD

**Issue by wikfeldt** [ENCCS/gpu-programming#4]
- confusing point: why kernels? why no explicit loops?
- drive home the logic with threadIds etc
- memory: can't expect to have non-contiguous arrays and get performance
- don't expect to get easy performance! First attempt might well be slower than CPU version

**Comment by csccva** [comment]
These guys (https://streamhpc.com/blog/2016-04-05/comparing-syntax-cuda-opencl-hip/)  seem to have found a general way to call the terms without ambiguity and have a good comparison between software environments.

**Comment by wikfeldt** [comment]
i think we can consider this to be done, so resolving
