### ISSUE TITLE
Examples Ep: adapt Numba-Python for GPU

### ISSUE THREAD

**Issue by stepas-toliautas** [ENCCS/gpu-programming#41]
Current code is accelerated by Numba JIT (almost to C++ performance), but is not offloaded to GPU yet.
Also, an alternative of main loop is in a comment, because one is faster with (CPU-)JIT, the other without it (using NumPy vectorization), and I'm not yet sure which form the GPU kernel will take.

**Comment by qianglise** [comment]
@stepas-toliautas  and @wikfeldt  made a version using numba CUDA, a few problems not solved yet
- the results are still wrong
- i have to remove all the constants, like dt, a, dx, dy

the code is here 
[stencil-numba-gpu](https://github.com/ENCCS/gpu-programming/tree/stencil-numba-gpu)

**Comment by stepas-toliautas** [comment]
The results are *accidentally* slightly wrong, because thread/block size is incorrect: if the second tuple is `(16, 16)`, then the first must be something like `(ceil(grid_side // 16), ceil(grid_side // 16))`. So now the code only touches small part of the grid. (You can check the generated images.) Setting the block sizes correctly yields *completely* wrong results 😀 , but uses the entire grid.
From my side I have a `gufunc` that works correctly and decently (I think slower than my initial JIT, but don't remember) on CPU, but **amazingly** slow on GPU (like "200x200x50 = 3 seconds" slow).

**Comment by stepas-toliautas** [comment]
Woo, found it!! 🥳 One of the indices in the kernel was accidentally copied wrong (I think), so it caused the grid to shift down-left one point every 4 iterations. Now the result is still not bit-accurate, but close enough to be a block-alignment issue or something similar. Also, in the beginning, `current` data was copied to device while `previous` was not, but computation actually started from `previous`... I'll try to massage everything out now.

**Comment by qianglise** [comment]
I have to use the following to get a bit better results
    d_curr=numba.cuda.to_device(current.data)
    d_prev=numba.cuda.to_device(previous.data)

allocating curr on the device  without copying the data yields worse results
d_curr=numba.cuda.device_array_like(d_curr)

**Comment by stepas-toliautas** [comment]
@qianglise : yep, noticed that too. Fixed what was left to fix, added all constants back, now testing and writing up.
Thanks a lot for your help!
